//! Platform-free representation of one multi-device switch attempt.
//!
//! A USB arrival is local evidence only: the receiving side cannot derive
//! which peer just departed, particularly in a group with more than two
//! devices. Therefore a [`SwitchTransaction`] is deliberately created from
//! the synchronized group snapshot by the source side, and is later delivered
//! to the target by the control plane. This module never guesses a peer from
//! an arrival event.

use crate::multidevice::{RouteError, RouteWrite, SwitchGroupSnapshot, SwitchRoute};
use serde::{Deserialize, Serialize};

/// A correlation identifier generated by the source runtime and persisted by
/// the service/control-plane layer when it is reachable.
///
/// It is opaque to the runtime: do not derive it from a timestamp or a device
/// ID, because that would make two rapid switch presses ambiguous. The
/// sidecar must generate it with a cryptographically secure random generator.
pub type SwitchTransactionId = String;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum TransactionPhase {
    /// The source saw its USB trigger group leave and should write the
    /// target's values immediately, before the target can run its correction.
    SourceFastPath,
    /// The target observed its trigger group arrive and should repeat exactly
    /// the values from the source plan.
    TargetArrivalCorrection,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct SwitchTransaction {
    pub id: SwitchTransactionId,
    pub group_id: String,
    pub group_revision: u64,
    pub source_device_id: String,
    pub source_port_index: u16,
    pub target_device_id: String,
    pub target_port_index: u16,
    /// The values are captured from the immutable group revision that created
    /// the transaction. Both paths use this exact list; later group edits do
    /// not mutate a switch already in flight.
    pub writes: Vec<RouteWrite>,
    pub issued_at_ms: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct TransactionWritePlan {
    pub transaction_id: SwitchTransactionId,
    pub phase: TransactionPhase,
    pub group_id: String,
    pub group_revision: u64,
    pub source_device_id: String,
    pub target_device_id: String,
    pub writes: Vec<RouteWrite>,
}

/// The target's immediate local action after USB arrival. It intentionally has
/// no transaction ID: daily switching must still work while the service is
/// unavailable. When the corresponding transaction is delivered later, its
/// write list must equal this correction plan.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LocalArrivalCorrection {
    pub group_id: String,
    pub group_revision: u64,
    pub local_device_id: String,
    pub writes: Vec<RouteWrite>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TransactionError {
    EmptyTransactionId,
    Route(RouteError),
    UnknownLocalDevice(String),
    NotTarget { expected: String, actual: String },
}

impl std::fmt::Display for TransactionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::EmptyTransactionId => write!(f, "switch transaction id is empty"),
            Self::Route(error) => write!(f, "cannot create switch transaction: {error}"),
            Self::UnknownLocalDevice(id) => {
                write!(f, "local device `{id}` is not in this switch group")
            }
            Self::NotTarget { expected, actual } => write!(
                f,
                "switch transaction targets `{expected}`, not local device `{actual}`"
            ),
        }
    }
}

impl std::error::Error for TransactionError {}

/// Build the correction path that a target may run as soon as its USB trigger
/// group arrives. This uses only its cached, validated group snapshot and is
/// deliberately independent of network delivery.
pub fn local_arrival_correction(
    snapshot: &SwitchGroupSnapshot,
    local_device_id: &str,
) -> Result<LocalArrivalCorrection, TransactionError> {
    snapshot
        .validate()
        .map_err(|error| TransactionError::Route(RouteError::InvalidGroup(error)))?;
    let device = snapshot
        .devices
        .iter()
        .find(|device| device.device_id == local_device_id)
        .ok_or_else(|| TransactionError::UnknownLocalDevice(local_device_id.to_string()))?;
    let mut writes = device
        .monitors
        .iter()
        .map(|monitor| RouteWrite {
            fingerprint: monitor.fingerprint.clone(),
            value: monitor.local_input,
        })
        .collect::<Vec<_>>();
    writes.sort_by(|a, b| a.fingerprint.cmp(&b.fingerprint));
    Ok(LocalArrivalCorrection {
        group_id: snapshot.group_id.clone(),
        group_revision: snapshot.revision,
        local_device_id: device.device_id.clone(),
        writes,
    })
}

impl SwitchTransaction {
    /// Create a transaction at the source's confirmed USB departure.
    ///
    /// `id` is created by the source runtime. The core accepts it explicitly
    /// so it can be persisted and delivered to the target later; it must not
    /// be a timestamp-derived identifier.
    pub fn begin(
        snapshot: &SwitchGroupSnapshot,
        source_device_id: &str,
        id: impl Into<SwitchTransactionId>,
        issued_at_ms: u64,
    ) -> Result<Self, TransactionError> {
        let id = id.into();
        if id.trim().is_empty() {
            return Err(TransactionError::EmptyTransactionId);
        }
        let route = snapshot
            .route_after_departure(source_device_id)
            .map_err(TransactionError::Route)?;
        Ok(Self::from_route(id, route, issued_at_ms))
    }

    fn from_route(id: SwitchTransactionId, route: SwitchRoute, issued_at_ms: u64) -> Self {
        Self {
            id,
            group_id: route.group_id,
            group_revision: route.revision,
            source_device_id: route.source_device_id,
            source_port_index: route.source_port_index,
            target_device_id: route.target_device_id,
            target_port_index: route.target_port_index,
            writes: route.writes,
            issued_at_ms,
        }
    }

    /// The source's immediate plan after `GroupLeft`.
    pub fn source_fast_path_plan(&self) -> TransactionWritePlan {
        self.plan(TransactionPhase::SourceFastPath)
    }

    /// The target's correction plan after its locally observed USB arrival.
    ///
    /// This is intentionally guarded by the expected target ID. Receiving an
    /// old or unrelated transaction must not cause a different group member to
    /// write DDC values merely because it happened to see a USB arrival.
    pub fn target_arrival_correction_plan(
        &self,
        local_device_id: &str,
    ) -> Result<TransactionWritePlan, TransactionError> {
        if self.target_device_id != local_device_id {
            return Err(TransactionError::NotTarget {
                expected: self.target_device_id.clone(),
                actual: local_device_id.to_string(),
            });
        }
        Ok(self.plan(TransactionPhase::TargetArrivalCorrection))
    }

    fn plan(&self, phase: TransactionPhase) -> TransactionWritePlan {
        TransactionWritePlan {
            transaction_id: self.id.clone(),
            phase,
            group_id: self.group_id.clone(),
            group_revision: self.group_revision,
            source_device_id: self.source_device_id.clone(),
            target_device_id: self.target_device_id.clone(),
            writes: self.writes.clone(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::multidevice::{GroupDevice, MonitorInput};

    fn monitor(fingerprint: &str, input: u16) -> MonitorInput {
        MonitorInput {
            fingerprint: fingerprint.into(),
            label: fingerprint.into(),
            local_input: input,
        }
    }

    fn group() -> SwitchGroupSnapshot {
        SwitchGroupSnapshot {
            group_id: "desk".into(),
            revision: 9,
            devices: vec![
                GroupDevice {
                    device_id: "mac".into(),
                    name: "Mac".into(),
                    port_index: 1,
                    monitors: vec![monitor("left", 15), monitor("right", 16)],
                },
                GroupDevice {
                    device_id: "windows".into(),
                    name: "Windows".into(),
                    port_index: 2,
                    monitors: vec![monitor("left", 17), monitor("right", 18)],
                },
            ],
        }
    }

    #[test]
    fn source_and_target_share_one_id_and_one_idempotent_write_list() {
        let tx = SwitchTransaction::begin(&group(), "mac", "txn-123", 42).unwrap();
        let source = tx.source_fast_path_plan();
        let target = tx.target_arrival_correction_plan("windows").unwrap();

        assert_eq!(source.transaction_id, "txn-123");
        assert_eq!(source.transaction_id, target.transaction_id);
        assert_eq!(source.writes, target.writes);
        assert_eq!(source.phase, TransactionPhase::SourceFastPath);
        assert_eq!(target.phase, TransactionPhase::TargetArrivalCorrection);
        assert_eq!(target.writes[0].value, 17);
        assert_eq!(target.writes[1].value, 18);
    }

    #[test]
    fn target_can_correct_from_its_cache_before_transaction_delivery() {
        let correction = local_arrival_correction(&group(), "windows").unwrap();
        let tx = SwitchTransaction::begin(&group(), "mac", "txn-123", 42).unwrap();

        assert_eq!(correction.group_revision, 9);
        assert_eq!(
            correction.writes,
            tx.target_arrival_correction_plan("windows").unwrap().writes
        );
    }

    #[test]
    fn arrival_on_a_non_target_is_rejected_instead_of_guessing() {
        let tx = SwitchTransaction::begin(&group(), "mac", "txn-123", 42).unwrap();
        assert_eq!(
            tx.target_arrival_correction_plan("mac").unwrap_err(),
            TransactionError::NotTarget {
                expected: "windows".into(),
                actual: "mac".into(),
            }
        );
    }

    #[test]
    fn transaction_id_must_be_supplied_explicitly() {
        assert_eq!(
            SwitchTransaction::begin(&group(), "mac", "   ", 42).unwrap_err(),
            TransactionError::EmptyTransactionId
        );
    }

    #[test]
    fn transaction_keeps_its_original_revision_and_values() {
        let mut snapshot = group();
        let tx = SwitchTransaction::begin(&snapshot, "mac", "txn-123", 42).unwrap();
        snapshot.revision = 10;
        snapshot.devices[1].monitors[0].local_input = 27;

        assert_eq!(tx.group_revision, 9);
        assert_eq!(tx.source_fast_path_plan().writes[0].value, 17);
    }

    #[test]
    fn unknown_arrival_device_is_rejected() {
        assert_eq!(
            local_arrival_correction(&group(), "other").unwrap_err(),
            TransactionError::UnknownLocalDevice("other".into())
        );
    }
}
